# Generated by Django 5.1.4 on 2025-01-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coffee_menu',
            new_name='CoffeeMenu',
        ),
    ]
