# Generated by Django 5.1.4 on 2025-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_coffeegallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeegallery',
            name='description',
        ),
        migrations.AddField(
            model_name='coffeegallery',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
