# Generated by Django 5.1.2 on 2025-01-23 17:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bloggallery_coffeeblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('image', models.ImageField(upload_to='coffee-about')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogGallery',
        ),
    ]
