# Generated by Django 5.1.2 on 2025-01-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_coffeeabout_coffeebanner_delete_bloggallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeabout',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coffeeabout',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='coffee-about'),
        ),
        migrations.AddField(
            model_name='coffeebanner',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
