# Generated by Django 5.1.2 on 2025-01-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_coffeeabout_date_created_coffeeabout_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeabout',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coffeebanner',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
