# Generated by Django 5.1.2 on 2025-01-24 06:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_coffeeabout_name_coffeebanner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeTopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Image', models.CharField(max_length=200, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coffeeabout',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
