# Generated by Django 5.1.2 on 2025-01-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_coffeetopmenu_alter_coffeeabout_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeetopmenu',
            name='Image',
        ),
        migrations.AddField(
            model_name='coffeetopmenu',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
