# Generated by Django 5.1.2 on 2025-01-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_coffeetopmenu_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeetopmenu',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
